import requests
import pandas as pd
import json

# Diccionario de equipos y sus URLs
equipos_urls = {
    "America": "https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTkx",
    "Monterrey": "https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTg1",
    "juarez":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHBqdm0tcHJ0bHdiLmxpZ2FtZXgubmV0L2FwaV9zaWlkLXYxL3NydmphdmFzbGN0QGhzPS58NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExNzk1",
    "pumas":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTg4",
    "tijuana":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTgw",
    "atlas":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMjQ1",
    "leon":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMjQz",
    "mazatlan":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTEyMDUx",
    "santon":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTky",
    "tigres":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTg2",
    "pachuca":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTg0",
    "chivas":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTgy",
    "toluca":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTg3",
    "queretaro":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTEyMDQy",
    "cruz azul":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTgx",
    "san luis":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExNzc4",
    "puebla":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExNTQz",
    "necaxa":"https://www.ligafemenil.mx/ws/aHR0cHM6Ly9hcHhqdm0tcHJ0bHdiLmxpZ2FteC5uZXQvYXBpX3NpaWQtdjEvc3J2amF2YXNsY3Q@aHNhaD18NTg5OGJiOWU1Y2JjNTljOTViZmEyOTYzYjMzNjYxZTZkNmE0OGYyNDllODIwOTIzYjcyNDlhMTg4YzA1NTMzZTJhMDgxY2VmNDU3ZjhjODM0YmY4ODM3ZWJhZjVjMzcxZjRlYTAwZDY2YWEzNDQ5YjEyMzRjYzQ3NjRhOTU5NzF8JnBzV2lkZ2V0PURTQ1BfU2dtdFRhcmpldGFzJm9ialRlbXBvcmFkYT03NSZvYmpUb3JuZW89MSZvYmpEaXZpc2lvbj0xNCZvYmpab25hPTAmb2JqSURDbHViPTExMTg5"

}
# Función para guardar JSON como CSV en formato tabular
def guardar_json_como_csv(nombre_equipo, url):
    try:
        # Realizar la solicitud GET
        respuesta = requests.get(url)
        respuesta.raise_for_status()  # Verificar errores
        datos = respuesta.json()  # Parsear la respuesta JSON

        # Acceder a la clave "DatosJSON"
        if "DatosJSON" in datos and isinstance(datos["DatosJSON"], list):
            df = pd.DataFrame(datos["DatosJSON"])  # Crear DataFrame a partir de la lista
        else:
            raise ValueError("El JSON no contiene una lista válida en 'DatosJSON'.")

        # Guardar DataFrame como CSV
        nombre_archivo = f"{nombre_equipo}.csv"
        df.to_csv(nombre_archivo, index=False, encoding='utf-8-sig')
        print(f"Guardado correctamente: {nombre_archivo}")
    except Exception as e:
        print(f"Error procesando {nombre_equipo}: {e}")

# Procesar cada equipo
for equipo, url in equipos_urls.items():
    guardar_json_como_csv(equipo, url)